# Generated by Django 4.0.3 on 2024-07-18 12:41

from django.db import migrations, models
import names_generator
import users.validator
import uuid


def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_user(
        username="abc",
        email="abc@gmail.com",
        password="abc@12345"
    )

def delete_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='abc').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ("users", "001_initial")
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEmotions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(editable=False, null=True)),
                ('expressions', models.FileField(upload_to='audio_emotions/%y', validators=[users.validator.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='AudioGrammerCorrections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(editable=False)),
                ('corrections', models.FileField(upload_to='corrections/%y', validators=[users.validator.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='AudioPronounciationQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(editable=False, null=True)),
                ('qualities', models.FileField(upload_to='pronounciations/%y', validators=[users.validator.file_size])),
                ('quality_with_timestamp', models.FileField(upload_to='pronounciations/%y', validators=[users.validator.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='AudioTranscriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(editable=False, null=True)),
                ('transcription', models.FileField(upload_to='transcriptions/%y', validators=[users.validator.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='FacialExpressions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.UUIDField(editable=False, null=True)),
                ('expressions', models.FileField(upload_to='video_emotions/%y', validators=[users.validator.file_size])),
                ('max_expression', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GrammerCorrectionsPPTX',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('pptx_id', models.UUIDField(editable=False)),
                ('corrected', models.FileField(upload_to='corrected_ppt/%y', validators=[users.validator.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='PPTX',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(default=names_generator.generate_name, max_length=100)),
                ('ppt', models.FileField(upload_to='ppt/%y', validators=[users.validator.file_size])),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(default=names_generator.generate_name, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='video/%y', validators=[users.validator.file_size])),
                ('audio', models.FileField(upload_to='audio/%y', validators=[users.validator.file_size])),
            ],
        ),
    ]
