# Generated by Django 4.0.3 on 2024-07-18 14:40

from django.db import migrations

def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_user(
        username="abc",
        email="abc@gmail.com",
        password="abc@12345"
    )

def delete_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='abc').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user, delete_default_user),
    ]
